contacts = [
  {
    birthday: {day: 20, month: 1, year: 1978},
    company: 'Creative Consulting',
    emailAddresses: [[Object]],
    familyName: 'Bell',
    givenName: 'Kate',
    hasThumbnail: false,
    imAddresses: [],
    jobTitle: 'Producer',
    middleName: '',
    phoneNumbers: [[Object], [Object]],
    postalAddresses: [[Object]],
    recordID: '177C371E-701D-42F8-A03B-C61CA31627F6',
    thumbnailPath: '',
    urlAddresses: [[Object]],
  },
  {
    company: '',
    emailAddresses: [[Object]],
    familyName: 'Higgins',
    givenName: 'Daniel',
    hasThumbnail: false,
    imAddresses: [],
    jobTitle: '',
    middleName: '',
    phoneNumbers: [[Object], [Object], [Object]],
    postalAddresses: [[Object]],
    recordID: 'AB211C5F-9EC9-429F-9466-B9382FF61035',
    thumbnailPath: '',
    urlAddresses: [],
  },
  {
    birthday: {day: 22, month: 6, year: 1980},
    company: '',
    emailAddresses: [[Object]],
    familyName: 'Appleseed',
    givenName: 'John',
    hasThumbnail: false,
    imAddresses: [],
    jobTitle: '',
    middleName: '',
    phoneNumbers: [[Object], [Object]],
    postalAddresses: [[Object], [Object]],
    recordID: '410FE041-5C4E-48DA-B4DE-04C15EA3DBAC',
    thumbnailPath: '',
    urlAddresses: [],
  },
  {
    birthday: {day: 29, month: 8, year: 1985},
    company: '',
    emailAddresses: [[Object]],
    familyName: 'Haro',
    givenName: 'Anna',
    hasThumbnail: false,
    imAddresses: [],
    jobTitle: '',
    middleName: '',
    phoneNumbers: [[Object]],
    postalAddresses: [[Object]],
    recordID: 'F57C8277-585D-4327-88A6-B5689FF69DFE',
    thumbnailPath: '',
    urlAddresses: [],
  },
  {
    company: 'Financial Services Inc.',
    emailAddresses: [[Object]],
    familyName: 'Zakroff',
    givenName: 'Hank',
    hasThumbnail: false,
    imAddresses: [],
    jobTitle: 'Portfolio Manager',
    middleName: 'M.',
    phoneNumbers: [[Object], [Object]],
    postalAddresses: [[Object]],
    recordID: '2E73EE73-C03F-4D5F-B1E8-44E85A70F170',
    thumbnailPath: '',
    urlAddresses: [],
  },
  {
    birthday: {day: 15, month: 6, year: 1998},
    company: '',
    emailAddresses: [],
    familyName: 'Taylor',
    givenName: 'David',
    hasThumbnail: false,
    imAddresses: [],
    jobTitle: '',
    middleName: '',
    phoneNumbers: [[Object]],
    postalAddresses: [[Object]],
    recordID: 'E94CD15C-7964-4A9B-8AC4-10D7CFB791FD',
    thumbnailPath: '',
    urlAddresses: [],
  },
  {
    company: '',
    emailAddresses: [],
    familyName: '',
    givenName: 'Hry',
    hasThumbnail: false,
    imAddresses: [],
    jobTitle: '',
    middleName: '',
    phoneNumbers: [[Object]],
    postalAddresses: [],
    recordID: '2EBD3211-6877-482E-AF4F-C696CB9E5187:ABPerson',
    thumbnailPath: '',
    urlAddresses: [],
  },
];
